### ISSUE TITLE
Implementasjon og test av autorisasjon/tilgangskontroll på API

### ISSUE THREAD

**Issue by torleifg** [Informasjonsforvaltning/data-service-catalog#7]

**Comment by NilsOveTen** [comment]
Det er 4 roller du må ta hensyn til
- `system:root:admin` -> skal ha lesetilgang til alle kataloger
- `organization:${catalogId}:admin` -> skal ha skrivetilgang til katalogen med id=catalogId
- `organization:${catalogId}:write` -> skal ha skrivetilgang til katalogen med id=catalogId
- `organization:${catalogId}:read` -> skal ha lesetilgang til katalogen med id=catalogId
